export const GET_ALL_MOVIES = "GET_ALL_MOVIES";
export const GET_ALL_MOVIES_SUCCESS = "GET_ALL_MOVIES_SUCCESS";
export const GET_ALL_MOVIES_FAILURE = "GET_ALL_MOVIES_FAILURE";

export const GET_ALL_UPCOMMINGS = "GET_ALL_UPCOMMINGS";
export const GET_ALL_UPCOMMINGS_SUCCESS = "GET_ALL_UPCOMMINGS_SUCCESS";
export const GET_ALL_UPCOMMINGS_FAILURE = "GET_ALL_UPCOMMINGS_FAILURE";

export const GET_ALL_TRENDINGS = "GET_ALL_TRENDINGS";
export const GET_ALL_TRENDINGS_SUCCESS = "GET_ALL_TRENDINGS_SUCCESS";
export const GET_ALL_TRENDINGS_FAILURE = "GET_ALL_TRENDINGS_FAILURE";

export const GET_ALL_PEOPLE = "GET_ALL_PEOPLE";
export const GET_ALL_PEOPLE_SUCCESS = "GET_ALL_PEOPLE_SUCCESS";
export const GET_ALL_PEOPLE_FAILURE = "GET_ALL_PEOPLE_FAILURE";

export const GET_MOVIE_DETAILS = "GET_MOVIE_DETAILS";
export const GET_MOVIE_DETAILS_SUCCESS = "GET_MOVIE_DETAILS_SUCCESS";
export const GET_MOVIE_DETAILS_FAILURE = "GET_MOVIE_DETAILS_FAILURE";

export const GET_PEOPLE_DETAILS = "GET_PEOPLE_DETAILS";
export const GET_PEOPLE_DETAILS_SUCCESS = "GET_PEOPLE_DETAILS_SUCCESS";
export const GET_PEOPLE_DETAILS_FAILURE = "GET_PEOPLE_DETAILS_FAILURE";
